imporve(mongodb): update the module to the format of the new version
alibabacloud-automation/terraform-alicloud-mongodb pull request #3
Opened 2020-01-08 11:00 UTC by Rich-yi

2020-01-09 01:21 UTC, xiaozhu36 requested changes

2020-01-09 01:21 UTC, xiaozhu36 commented on variables.tf
> +variable "create_instance" {
只有一个资源，叫create就行

2020-01-09 01:21 UTC, xiaozhu36 commented on variables.tf
> +  description = "Mongodb Instance backup period."
description 中说清楚，有哪些可选值

2020-01-09 01:21 UTC, xiaozhu36 commented on variables.tf
>    description = "The engine version to use"
engine version说清楚有哪些可选值

2020-01-09 01:21 UTC, xiaozhu36 commented on variables.tf
> +#variables for alicloud_mongodb_instance
就 Mongodb Instance

2020-01-09 01:21 UTC, xiaozhu36 commented on outputs.tf
> +  description = "`(Deprecated)` It has been deprecated and use `this_Mongodb_instance_id` instead."
this_mongodb_instance_id

2020-01-09 01:21 UTC, xiaozhu36 commented on outputs.tf
> +  description = "Mongodb vswitch id in which the Rds instance."
description = "The vswitch id in which the mongodb instance."

2020-01-09 01:21 UTC, xiaozhu36 commented on outputs.tf
> +  description = "Mongodb zone id in which the Rds instance."
description = "The zone id in which the mongodb instance."

2020-01-09 01:21 UTC, xiaozhu36 commented on outputs.tf
> +  description = "Mongodb instance charge period when Prepaid."
when PrePaid

2020-01-09 01:21 UTC, xiaozhu36 commented on modules/mongodb/variables.tf
> +}
submodules 中的按照主module中的改

2020-01-09 01:21 UTC, xiaozhu36 commented on main.tf
> +//security_ip_list
不用的就去掉

2020-01-09 01:21 UTC, xiaozhu36 commented on locals.tf
> +  create_more_resources = var.existing_instance_id != "" || var.create_instance ? true : false
这里面应该没有create_more_resources

2020-01-09 01:21 UTC, xiaozhu36 commented on examples/mongodb/output.tf
> +  value       = module.mongodb_example.this_mongodb_instance_backup_time
example中的也按照主Module中的改

2020-01-09 01:21 UTC, xiaozhu36 commented on examples/mongodb/main.tf
> +  enable_details              = true
enable_details需要么？

2020-01-09 01:21 UTC, xiaozhu36 commented on examples/mongodb/main.tf
> +  name              = "redis_vpc"
怎么还有redis

2020-01-09 01:22 UTC, xiaozhu36 requested changes

2020-01-09 01:22 UTC, xiaozhu36 commented on modules/mongodb/outputs.tf
> +  value       = module.mongodb.this_mongodb_instance_backup_time
submodule的readme呢

2020-01-09 11:26 UTC, xiaozhu36 requested changes

2020-01-09 11:26 UTC, xiaozhu36 commented on README-CN.md
> +# terraform-alicloud-mongodb
中英文的README这个按照https://github.com/terraform-alicloud-modules/terraform-alicloud-redis/pull/6 在改改

2020-01-09 11:26 UTC, xiaozhu36 commented on modules/mongodb/README.md
> +  version = "~> 2.0"
这个改成 1.2

2020-01-09 11:26 UTC, xiaozhu36 commented on modules/mongodb/main.tf
> +  engine_version       = var.engine_version
这个地方应该是要分版本，几个节点，什么类型

2020-01-09 11:26 UTC, xiaozhu36 commented on modules/mongodb/variables.tf
> +  description = "A mapping of tags to assign to the resource."
A mapping of tags to assign to the mongodb instance resource.

2020-01-09 11:26 UTC, xiaozhu36 commented on variables.tf
> +  description = "A mapping of tags to assign to the resource."
这个也一样

2020-01-09 11:26 UTC, xiaozhu36 commented on variables.tf
> +  description = "`(Deprecated)` It has been deprecated from version 2.0.0 and use `existing_instance_id` instead."
下个版本是1.2.0，不是2.0.0

2020-01-09 11:26 UTC, xiaozhu36 commented on outputs.tf
> +  description = "`(Deprecated)` It has been deprecated and use `this_mongodb_instance_zone_id` instead."
写清楚从1.2.0 开始弃用

2020-01-10 04:11 UTC, xiaozhu36 requested changes

2020-01-10 04:11 UTC, xiaozhu36 commented on README-CN.md
> +# terraform-alicloud-mongodb
第二行前面的 # 去掉

2020-01-10 04:11 UTC, xiaozhu36 commented on examples/mongodb/main.tf
> +  source               = "../../modules/mongodb-3.4-rock-db"
mongodb-3.4-rocksdb

2020-01-10 04:11 UTC, xiaozhu36 commented on examples/mongodb/output.tf
> +  description = "The Zone to launch the MongoDB instance. it supports multiple zone."
it supports multiple zone 可以去掉

2020-01-10 04:11 UTC, xiaozhu36 commented on modules/mongodb-3.4-rock-db/variables.tf
> +  description = "The storage space of the instance.Valid values:10to3000. Unit: GB.You can only specify this value in 10 GB increments."
10to3000 -》 10 to 3000

2020-01-10 04:11 UTC, xiaozhu36 commented on modules/mongodb-3.4-rock-db/variables.tf
> +  description = "The ID of the zone. You can call thehttps://www.alibabacloud.com/help/doc-detail/61933.htm to query zones.. "
You can refer to https://www.alibabacloud.com/help/doc-detail/61933.htm. 

如果你发现provider上的文档有问题，也要即得改下，然后提交一个PR

2020-01-10 04:11 UTC, xiaozhu36 commented on modules/mongodb-3.4-rock-db/variables.tf
> +  description = "The number of nodes in the replica set instance. Valid values:3,5, and7. Default value:3."
Valid values: 3, 5, 7. Default to 3.

2020-01-10 04:11 UTC, xiaozhu36 commented on modules/mongodb-3.4-wired-tiger/README.md
> +# Alibaba Cloud MongoDB-3.4-WiredTiger Terraform Module
mongodb-3.4-wiredtiger

2020-01-10 04:11 UTC, xiaozhu36 commented on variables.tf
> +  description = "Whether to create security group. If false, you can use a existing Mongodb instance by setting `existing_instance_id`."
security group?
use an existing Mongodb

2020-01-10 06:19 UTC, Rich-yi commented on modules/mongodb-3.4-rock-db/variables.tf
> +  description = "The ID of the zone. You can call thehttps://www.alibabacloud.com/help/doc-detail/61933.htm to query zones.. "
外网的帮助文档

2020-01-10 06:48 UTC, xiaozhu36 requested changes

2020-01-10 06:48 UTC, xiaozhu36 commented on README-CN.md
> +  name                 = "mongoUser"
name 就别用user了，这个是个实例，用 my-mongo

2020-01-10 06:48 UTC, xiaozhu36 commented on README-CN.md
> +
参考这个： https://github.com/terraform-alicloud-modules/terraform-alicloud-redis/blob/master/README-CN.md#%E6%A8%A1%E6%9D%BF 把子module也加下

2020-01-10 06:48 UTC, xiaozhu36 commented on examples/mongodb/main.tf
> +  source               = "../../modules/mongodb-3.4-rockdb"
rocksdb不是rockdb

2020-01-10 06:48 UTC, xiaozhu36 commented on modules/mongodb-3.4-rockdb/main.tf
> +  tags                 = var.tags
tags改成这种吧，吧类型加上：
```
tags                 = merge(
   {
      EngineVersion = local.engine_version
      StorageEngine = local.storage_engine
    }
    var.tags
)
```

2020-01-10 06:48 UTC, xiaozhu36 commented on modules/mongodb-3.4-rockdb/main.tf
> +  tags                 = var.tags
以后的都可以这么加，把一些重要的加上，但是不宜太多，不超过2个

2020-01-10 06:48 UTC, xiaozhu36 commented on variables.tf
> +  description = "The version number of the database. Valid value:3.2,3.4or4.0."
这个怎么没改啊，3.2, 3.4, 4.0.

2020-01-10 06:48 UTC, xiaozhu36 commented on variables.tf
> +  description = "The MongoDB storage engine, WiredTiger or RocksDB.Default value: WiredTiger."
注意语法，. 之后要保留一个空格

2020-01-10 08:20 UTC, xiaozhu36 requested changes

2020-01-10 08:20 UTC, xiaozhu36 commented on README-CN.md
> +* [mongodb-3.4-rocksdb](https://github.com/terraform-alicloud-mongodb/tree/mongodb/modules/mongodb-3.4-rockdb)
这个地址不对吧，最后的应该是 mongodb-3.4-rocksdb

2020-01-10 08:20 UTC, xiaozhu36 commented on modules/mongodb-3.4-rocksdb/variables.tf
> +  description = "The storage space of the instance.Valid values:10 to 3000. Unit: GB.You can only specify this value in 10 GB increments. "
Valid values: 10 to 3000. 中间是有空格的。

2020-01-10 08:20 UTC, xiaozhu36 commented on modules/mongodb-3.4-rocksdb/variables.tf
> +  description = "The specification of the instance. For more information about the value, seehttps://www.alibabacloud.com/help/doc-detail/57141.htm"
see https://xxx 中间是有空格的

2020-01-10 08:20 UTC, xiaozhu36 commented on modules/mongodb-3.4-rocksdb/variables.tf
> +  description = "The number of nodes in the replica set instance. Valid values:3, 5, 7. Default value: 3. "
Valid values: 3, 5, 7 中间是有空格的

2020-01-10 08:20 UTC, xiaozhu36 commented on modules/mongodb-3.4-wiredtiger/variables.tf
> +  description = "The specification of the instance. For more information about the value, seehttps://www.alibabacloud.com/help/doc-detail/57141.htm"
这些也都一样

2020-01-10 08:20 UTC, xiaozhu36 commented on variables.tf
> +  description = "The MongoDB storage engine, WiredTiger or RocksDB.Default value: WiredTiger. "
中间的空格

2020-01-10 08:56 UTC, xiaozhu36 approved these changes

2020-01-10 08:56 UTC, merged